server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/spring-security-v2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true